### ISSUE TITLE
[code2seq] 2 inputs

### ISSUE THREAD

**Issue by natalymr** [natalymr/gcm#22]

**Comment by natalymr** [comment]
## 1
```
grad acc (every 2-nd)
data:
  home: /home/ubuntu/gcm/commit2seq/code2seq/data/two_input
  dict: /two_input.dict.c2s
  train: /train
  valid: /val
  test: /test


training:
  batch_size: 25
  num_epochs: 30
  lr: 0.001
  teacher_forcing_rate: 0.4
  nesterov: True
  weight_decay: 0.01
  momentum: 0.95
  decay_ratio: 0.95
  save_name: /model.pth
  warm_up: 1
  patience: 30


model:
  token_size: 200
  hidden_size: 200
  num_layers: 2
  bidirectional: True
  rnn_dropout: 0.5
  embeddings_dropout: 0.3
  num_k : 800

etc:
  info_prefix: code2seq
  slack_url_path: ../slack/slack_url.yml
```
https://app.wandb.ai/natalymr/commit2seq-2-input/runs/pgvlzcs4?workspace=user-natalymr

## 2
```
grad acc (every 2-nd)
data:
  home: /home/ubuntu/gcm/commit2seq/code2seq/data/two_input
  dict: /two_input.dict.c2s
  train: /train
  valid: /val
  test: /test


training:
  batch_size: 25
  num_epochs: 30
  lr: 0.001
  teacher_forcing_rate: 0.5
  nesterov: True
  weight_decay: 0.01
  momentum: 0.95
  decay_ratio: 0.95
  save_name: /model.pth
  warm_up: 1
  patience: 30


model:
  token_size: 200
  hidden_size: 200
  num_layers: 1
  bidirectional: True
  rnn_dropout: 0.5
  embeddings_dropout: 0.3
  num_k : 800
```
https://app.wandb.ai/natalymr/commit2seq-2-input/runs/6tlcoo93?workspace=user-natalymr

## 3
```
grad acc (every 2-nd)
data:
  home: /home/ubuntu/gcm/commit2seq/code2seq/data/two_input
  dict: /two_input.dict.c2s
  train: /train
  valid: /val
  test: /test


training:
  batch_size: 28
  num_epochs: 30
  lr: 0.01
  teacher_forcing_rate: 0.5
  nesterov: True
  weight_decay: 0.01
  momentum: 0.95
  decay_ratio: 0.95
  save_name: /model.pth
  warm_up: 1
  patience: 30


model:
  token_size: 200
  hidden_size: 200
  num_layers: 1
  bidirectional: True
  rnn_dropout: 0.5
  embeddings_dropout: 0.3
  num_k : 600
```
https://app.wandb.ai/natalymr/commit2seq-2-input/runs/kvkitooa

---------
# Весь датасет
## 4 
```
data:
  home: /home/ubuntu/gcm/commit2seq/code2seq/data/two_input
  dict: /two_input.dict.c2s
  train: /train
  valid: /val
  test: /test


training:
  batch_size: 20
  num_epochs: 30
  lr: 0.01
  teacher_forcing_rate: 0.5
  nesterov: True
  weight_decay: 0.01
  momentum: 0.95
  decay_ratio: 0.95
  save_name: /model.pth
  warm_up: 1
  patience: 30


model:
  token_size: 200
  hidden_size: 200
  num_layers: 1
  bidirectional: True
  rnn_dropout: 0.5
  embeddings_dropout: 0.3
  num_k : 400
```
https://app.wandb.ai/natalymr/commit2seq-2-input/runs/5iy1q285
не понимаю из-за чего, связь с машиной прервалась через 6-8 часов после запуска, перезапустила:
https://app.wandb.ai/natalymr/commit2seq-2-input/runs/45zpa1dc
через screen - https://app.wandb.ai/natalymr/commit2seq-2-input/runs/y4cfpj7q?workspace=user-natalymr
такой же запуск, но с сохранением весов на каждом шаге: https://app.wandb.ai/natalymr/commit2seq-2-input/runs/wa5ke2gr
